# Generated by Django 3.1.2 on 2020-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201002_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.TextField(default='Pending'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='myfile',
            field=models.FileField(default='documents/defimage.jpg', upload_to='documents/'),
        ),
    ]
