# Generated by Django 3.1.2 on 2020-10-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201003_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_staff',
        ),
    ]
